openapi: 3.1.0
info:
  version: 0.1.0
  title: VASP API
  description: |
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://dev.vasp/api/v1

tags:
  - name: Authentication
    description: |
      ### Authentication Instructions

      To authenticate requests, include the following header:
      - `Authorization: Bearer <your_token>`

      > ⚠️ This header must be present in **protected requests**.

      #### Sample Headers
      ```javascript
      const headers = {
        'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
      };
      ```

  - name: Users Endpoints
    description: |
      Endpoints related to user management and authentication.

  - name: VASP Endpoints
    description: |
      Endpoints related to Virtual Asset Service Providers (VASPs).

  - name: Wallets Endpoints
    description: |
      Endpoints related to wallet management.

  - name: On-Ramp Transaction Endpoints
    description: |
      Endpoints for managing on-ramp transactions, including creation, cancellation and so on.

  - name: Off-Ramp Transaction Endpoints
    description: |
      Endpoints for managing off-ramp transactions, including creation, approval, cancellation and so on.

  - name: Webhook Endpoints
    description: |
      Endpoints for receiving webhook notifications from external services.

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Include JWT token in Authorization header as:
        `Authorization: Bearer <token>`

security:
  - jwt: []

paths:
  "/users":
    $ref: paths/users.yaml
  "/users/register":
    $ref: paths/users_register.yaml
  "/users/login":
    $ref: paths/users_login.yaml

  "/wallets":
    $ref: paths/wallets.yaml

  "/vasps/list":
    $ref: paths/vasps_list.yaml

  "/onramp/quotes/list":
    $ref: paths/onRamp/quotes_list.yaml
  "/onramp/transactions":
    $ref: paths/onRamp/transactions.yaml
  "/onramp/transactions/deposit":
    $ref: paths/onRamp/transactions_deposit.yaml
  "/onramp/transactions/{id}":
    $ref: paths/onRamp/transactions_{id}.yaml
  "/onramp/transactions/list":
    $ref: paths/onRamp/transactions_list.yaml

  "/offramp/quotes/list":
    $ref: paths/offRamp/quotes_list.yaml
  "/offramp/transactions":
    $ref: paths/offRamp/transactions.yaml
  "/offramp/transactions/cancel":
    $ref: paths/offRamp/transactions_cancel.yaml
  "/offramp/transactions/approve":
    $ref: paths/offRamp/transactions_approve.yaml
  "/offramp/transactions/accept":
    $ref: paths/offRamp/transactions_accept.yaml
  "/offramp/transactions/reject":
    $ref: paths/offRamp/transactions_reject.yaml
  "/offramp/transactions/transfer":
    $ref: paths/offRamp/transactions_transfer.yaml
  "/offramp/transactions/complete":
    $ref: paths/offRamp/transactions_complete.yaml
  "/offramp/transactions/{id}":
    $ref: paths/offRamp/transactions_{id}.yaml
  "/offramp/transactions/list":
    $ref: paths/offRamp/transactions_list.yaml

  "/webhook":
    $ref: paths/webhook.yaml
